import { CmsConfig } from "@/lib/cms";

export const pagesCmsConfig: CmsConfig = {
  entity: "pages",
  title: "Pages",
  layout: "pages",
  subtitle: "Manage website pages and dynamic section content",
  addLabel: "Add Page",
  searchPlaceholder: "Search pages...",
  groups: [
    { key: "basic", label: "Basic Information", column: "left" },
    { key: "hero", label: "Hero Section", column: "left" },
    { key: "content", label: "Main Content", column: "left" },
    { key: "sections", label: "Dynamic Sections", column: "left" },
    { key: "seo", label: "SEO", column: "right" },
    { key: "settings", label: "Settings", column: "right" },
  ],
  fields: [
    {
      key: "title",
      label: "Page Title",
      type: "text",
      group: "basic",
      column: "left",
      required: true,
    },
    {
      key: "slug",
      label: "Slug",
      type: "text",
      group: "basic",
      column: "left",
    },
    {
      key: "pageType",
      label: "Page Type",
      type: "select",
      group: "basic",
      column: "left",
      defaultValue: "standard",
      options: [
        { label: "Home Page", value: "home" },
        { label: "Standard Page", value: "standard" },
        { label: "Contact Page", value: "contact" },
        { label: "About Page", value: "about" },
      ],
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      group: "settings",
      column: "right",
      defaultValue: "draft",
      options: [
        { label: "Draft", value: "draft" },
        { label: "Published", value: "published" },
      ],
    },

    {
      key: "heroTitle",
      label: "Hero Title",
      type: "text",
      group: "hero",
      column: "left",
    },
    {
      key: "heroSubtitle",
      label: "Hero Subtitle",
      type: "textarea",
      group: "hero",
      column: "left",
    },
    {
      key: "image",
      label: "Hero Image",
      type: "image",
      group: "hero",
      column: "left",
    },
    {
      key: "herovideo",
      label: "Hero Video",
      type: "video",
      group: "hero",
      column: "left",
    },
    {
      key: "description",
      label: "Main Content",
      type: "textarea",
      group: "content",
      column: "left",
    },
    {
      key: "servicesMode",
      label: "Services Section",
      type: "select",
      group: "sections",
      column: "left",
      defaultValue: "hidden",
      options: [
        { label: "Hidden", value: "hidden" },
        { label: "Manual", value: "manual" },
        { label: "Linked", value: "linked" },
        { label: "Auto", value: "auto" },
      ],
    },
    {
      key: "servicesHeading",
      label: "Services Heading",
      type: "text",
      group: "sections",
      column: "left",
      showWhen: {
        key: "servicesMode",
        operator: "notEquals",
        value: "hidden",
      },
    },
    {
      key: "serviceItems",
      label: "Manual Services",
      type: "repeater",
      group: "sections",
      column: "left",
      showWhen: {
        key: "servicesMode",
        value: "manual",
      },
      fields: [
        { key: "title", label: "Title", type: "text" },
        { key: "description", label: "Description", type: "textarea" },
        { key: "image", label: "Image", type: "image" },
      ],
    },
    {
      key: "serviceIds",
      label: "Select Services",
      type: "relation-multiselect",
      group: "sections",
      column: "left",
      showWhen: {
        key: "servicesMode",
        value: "linked",
      },
      relation: {
        endpoint: "/content/services",
        labelKey: "title",
        valueKey: "_id",
      },
    },
    {
      key: "servicesLimit",
      label: "Services Count",
      type: "number",
      group: "sections",
      column: "left",
      defaultValue: 6,
      showWhen: {
        key: "servicesMode",
        value: "auto",
      },
    },
    {
      key: "testimonialsMode",
      label: "Testimonials Section",
      type: "select",
      group: "sections",
      column: "left",
      defaultValue: "hidden",
      options: [
        { label: "Hidden", value: "hidden" },
        { label: "Manual", value: "manual" },
        { label: "Linked", value: "linked" },
        { label: "Auto", value: "auto" },
      ],
    },
    {
      key: "testimonialsHeading",
      label: "Testimonials Heading",
      type: "text",
      group: "sections",
      column: "left",
      showWhen: {
        key: "testimonialsMode",
        operator: "notEquals",
        value: "hidden",
      },
    },
    {
      key: "testimonialItems",
      label: "Manual Testimonials",
      type: "repeater",
      group: "sections",
      column: "left",
      showWhen: {
        key: "testimonialsMode",
        value: "manual",
      },
      fields: [
        { key: "name", label: "Name", type: "text" },
        { key: "designation", label: "Designation", type: "text" },
        { key: "quote", label: "Quote", type: "textarea" },
        { key: "image", label: "Photo", type: "image" },
      ],
    },
    {
      key: "testimonialIds",
      label: "Select Testimonials",
      type: "relation-multiselect",
      group: "sections",
      column: "left",
      showWhen: {
        key: "testimonialsMode",
        value: "linked",
      },
      relation: {
        endpoint: "/content/testimonials",
        labelKey: "title",
        valueKey: "_id",
      },
    },
    {
      key: "testimonialsLimit",
      label: "Testimonials Count",
      type: "number",
      group: "sections",
      column: "left",
      defaultValue: 3,
      showWhen: {
        key: "testimonialsMode",
        value: "auto",
      },
    },
    {
      key: "projectsMode",
      label: "Projects Section",
      type: "select",
      group: "sections",
      column: "left",
      defaultValue: "hidden",
      options: [
        { label: "Hidden", value: "hidden" },
        { label: "Manual", value: "manual" },
        { label: "Linked", value: "linked" },
        { label: "Auto", value: "auto" },
      ],
    },
    {
      key: "projectsHeading",
      label: "Projects Heading",
      type: "text",
      group: "sections",
      column: "left",
      showWhen: {
        key: "projectsMode",
        operator: "notEquals",
        value: "hidden",
      },
    },
    {
      key: "projectItems",
      label: "Manual Projects",
      type: "repeater",
      group: "sections",
      column: "left",
      showWhen: {
        key: "projectsMode",
        value: "manual",
      },
      fields: [
        { key: "title", label: "Title", type: "text" },
        { key: "description", label: "Description", type: "textarea" },
        { key: "image", label: "Image", type: "image" },
      ],
    },
    {
      key: "projectIds",
      label: "Select Projects",
      type: "relation-multiselect",
      group: "sections",
      column: "left",
      showWhen: {
        key: "projectsMode",
        value: "linked",
      },
      relation: {
        endpoint: "/content/projects",
        labelKey: "title",
        valueKey: "_id",
      },
    },
    {
      key: "projectsLimit",
      label: "Projects Count",
      type: "number",
      group: "sections",
      column: "left",
      defaultValue: 6,
      showWhen: {
        key: "projectsMode",
        value: "auto",
      },
    },
    {
      key: "cardsMode",
      label: "Feature Cards Section",
      type: "select",
      group: "sections",
      column: "left",
      defaultValue: "hidden",
      options: [
        { label: "Hidden", value: "hidden" },
        { label: "Manual", value: "manual" },
        { label: "Linked", value: "linked" },
      ],
    },
    {
      key: "cardsHeading",
      label: "Cards Heading",
      type: "text",
      group: "sections",
      column: "left",
      showWhen: {
        key: "cardsMode",
        operator: "notEquals",
        value: "hidden",
      },
    },
    {
      key: "cardItems",
      label: "Manual Cards",
      type: "repeater",
      group: "sections",
      column: "left",
      showWhen: {
        key: "cardsMode",
        value: "manual",
      },
      fields: [
        { key: "title", label: "Title", type: "text" },
        { key: "description", label: "Description", type: "textarea" },
        { key: "icon", label: "Icon", type: "icon" },
      ],
    },
    {
      key: "linkedCardIds",
      label: "Select Cards",
      type: "relation-multiselect",
      group: "sections",
      column: "left",
      showWhen: {
        key: "cardsMode",
        value: "linked",
      },
      relation: {
        endpoint: "/content/cards",
        labelKey: "title",
        valueKey: "_id",
      },
    },

    {
      key: "contactDetails",
      label: "Contact Details",
      type: "repeater",
      group: "sections",
      column: "left",
      showWhen: {
        key: "pageType",
        value: "contact",
      },
      fields: [
        { key: "label", label: "Label", type: "text" },
        { key: "value", label: "Value", type: "text" },
        { key: "icon", label: "Icon", type: "icon" },
      ],
    },
    {
      key: "officeCards",
      label: "Office Cards",
      type: "repeater",
      group: "sections",
      column: "left",
      showWhen: {
        key: "pageType",
        value: "contact",
      },
      fields: [
        { key: "title", label: "Office Title", type: "text" },
        { key: "address", label: "Address", type: "textarea" },
        { key: "phone", label: "Phone", type: "text" },
        { key: "email", label: "Email", type: "text" },
      ],
    },

    {
      key: "metaTitle",
      label: "Meta Title",
      type: "text",
      group: "seo",
      column: "right",
    },
    {
      key: "metaDescription",
      label: "Meta Description",
      type: "textarea",
      group: "seo",
      column: "right",
    },
    {
      key: "sortOrder",
      label: "Sort Order",
      type: "number",
      group: "settings",
      column: "right",
      defaultValue: 0,
    },
  ],
};
