import { CmsConfig } from "@/lib/cms";

export const projectsCmsConfig: CmsConfig = {
  entity: "projects",
  title: "Projects",
  layout: "editor",
  subtitle: "Manage real estate project listings and detail page content",
  addLabel: "Add Project",
  searchPlaceholder: "Search projects...",
  groups: [
    { key: "basic", label: "Basic Information", column: "left" },
    { key: "hero", label: "Hero Section", column: "left" },
    { key: "specs", label: "Project Specifications", column: "left" },
    { key: "overview", label: "Overview Section", column: "left" },
    { key: "gallery", label: "Gallery", column: "left" },
    { key: "cta", label: "CTA Section", column: "left" },
    { key: "seo", label: "SEO", column: "right" },
    { key: "settings", label: "Settings", column: "right" },
  ],
  fields: [
    {
      key: "title",
      label: "Project Title",
      type: "text",
      group: "basic",
      column: "left",
      required: true,
    },
    {
      key: "slug",
      label: "Slug",
      type: "text",
      group: "basic",
      column: "left",
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      group: "settings",
      column: "right",
      defaultValue: "draft",
      options: [
        { label: "Draft", value: "draft" },
        { label: "Published", value: "published" },
      ],
    },
    {
      key: "category",
      label: "Category",
      type: "select",
      group: "basic",
      column: "left",
      options: [
        { label: "Luxury", value: "luxury" },
        { label: "Investment", value: "investment" },
        { label: "Apartments", value: "apartments" },
        { label: "Villa", value: "villa" },
        { label: "Townhouse", value: "townhouse" },
        { label: "Waterfront", value: "waterfront" },
      ],
    },
    {
      key: "signatureLabel",
      label: "Signature Label",
      type: "text",
      group: "basic",
      column: "left",
      placeholder: "Signature Residence",
    },

    {
      key: "image",
      label: "Hero Image",
      type: "image",
      group: "hero",
      column: "left",
    },
    {
      key: "locationLabel",
      label: "Location",
      type: "text",
      group: "hero",
      column: "left",
      placeholder: "Downtown Dubai, Dubai",
    },
    {
      key: "shortDescription",
      label: "Hero Description",
      type: "textarea",
      group: "hero",
      column: "left",
    },

    {
      key: "startingPrice",
      label: "Starting Price",
      type: "text",
      group: "specs",
      column: "left",
      placeholder: "From AED 2.3M",
    },
    {
      key: "bedrooms",
      label: "Bedrooms",
      type: "text",
      group: "specs",
      column: "left",
      placeholder: "2–8 Bedrooms",
    },
    {
      key: "sizeRange",
      label: "Size Range",
      type: "text",
      group: "specs",
      column: "left",
      placeholder: "2,800 – 7,200 sq.ft.",
    },
    {
      key: "community",
      label: "Community / Area",
      type: "text",
      group: "specs",
      column: "left",
      placeholder: "Downtown Dubai",
    },
    {
      key: "developer",
      label: "Developer",
      type: "text",
      group: "specs",
      column: "left",
      placeholder: "Emaar",
    },
    {
      key: "propertyType",
      label: "Property Type",
      type: "text",
      group: "specs",
      column: "left",
      placeholder: "Villa / Apartment / Townhouse",
    },
    {
      key: "handover",
      label: "Handover",
      type: "text",
      group: "specs",
      column: "left",
      placeholder: "Q4 2029",
    },

    {
      key: "overviewHeading",
      label: "Overview Heading",
      type: "text",
      group: "overview",
      column: "left",
      defaultValue: "Project Overview",
    },
    {
      key: "description",
      label: "Overview Description",
      type: "textarea",
      group: "overview",
      column: "left",
    },
    {
      key: "overviewPoints",
      label: "Overview Bullet Points",
      type: "repeater",
      group: "overview",
      column: "left",
      fields: [{ key: "text", label: "Point", type: "text" }],
    },
    {
      key: "highlightCards",
      label: "Why It Stands Out Cards",
      type: "repeater",
      group: "overview",
      column: "left",
      fields: [
        { key: "title", label: "Title", type: "text" },
        { key: "description", label: "Description", type: "textarea" },
      ],
    },

    {
      key: "gallery",
      label: "Gallery Images",
      type: "repeater",
      group: "gallery",
      column: "left",
      fields: [
        { key: "image", label: "Image", type: "image" },
        { key: "alt", label: "Alt Text", type: "text" },
      ],
    },

    {
      key: "ctaTitle",
      label: "CTA Title",
      type: "text",
      group: "cta",
      column: "left",
      defaultValue:
        "Let’s help you evaluate the right opportunity with more clarity",
    },
    {
      key: "ctaDescription",
      label: "CTA Description",
      type: "textarea",
      group: "cta",
      column: "left",
      defaultValue:
        "Speak with our team for brochure access, floor plans, pricing, availability, and personalized project guidance.",
    },
    {
      key: "primaryButtonLabel",
      label: "Primary Button Label",
      type: "text",
      group: "cta",
      column: "left",
      defaultValue: "Request Brochure",
    },
    {
      key: "secondaryButtonLabel",
      label: "Secondary Button Label",
      type: "text",
      group: "cta",
      column: "left",
      defaultValue: "Book Consultation",
    },

    {
      key: "metaTitle",
      label: "Meta Title",
      type: "text",
      group: "seo",
      column: "right",
    },
    {
      key: "metaDescription",
      label: "Meta Description",
      type: "textarea",
      group: "seo",
      column: "right",
    },
    {
      key: "sortOrder",
      label: "Sort Order",
      type: "number",
      group: "settings",
      column: "right",
      defaultValue: 0,
    },
  ],
};
