import { CmsConfig } from "@/lib/cms";

export const propertyTypeCmsConfig: any = {
  entity: "property-types",
  title: "Property Types",
  subtitle: "Manage property type master records",
  addLabel: "Add Property Type",
  searchPlaceholder: "Search property types...",
  groups: [
    { key: "basic", label: "Basic Information", column: "left" },
    { key: "media", label: "Media & Icon", column: "left" },
    { key: "settings", label: "Settings", column: "right" },
  ],
  fields: [
    {
      key: "title",
      label: "Title",
      type: "text",
      group: "basic",
      column: "left",
      required: true,
      note: "Example: Apartment, Villa, Townhouse",
    },
    {
      key: "slug",
      label: "Slug",
      type: "text",
      group: "basic",
      column: "left",
      note: "Leave blank if you want backend to normalize from title.",
    },
    {
      key: "description",
      label: "Description",
      type: "textarea",
      group: "basic",
      column: "left",
      note: "Short description for this property type.",
    },
    {
      key: "icon",
      label: "Icon",
      type: "icon",
      group: "media",
      column: "left",
      note: "Choose an icon for card/list usage.",
    },
    {
      key: "image",
      label: "Image",
      type: "image",
      group: "media",
      column: "left",
      note: "Optional preview/banner image.",
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      group: "settings",
      column: "right",
      defaultValue: "active",
      options: [
        { label: "Active", value: "active" },
        { label: "Inactive", value: "inactive" },
      ],
    },
    {
      key: "sortOrder",
      label: "Sort Order",
      type: "number",
      group: "settings",
      column: "right",
      defaultValue: 0,
      note: "Lower numbers appear first.",
    },
    {
      key: "isFeatured",
      label: "Featured",
      type: "boolean",
      group: "settings",
      column: "right",
      defaultValue: false,
    },
  ],
};
